apiVersion: skaffold/v1alpha5
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - context: ./
      image: gcr.io/s9-demo/tellmeall
  local:
    push: true
    useDockerCLI: false
deploy:
  kubectl:
    manifests:
      - deployments/tellmeall.yaml